--
-- CueStack Hybrid Schema
-- 基于 slack-clone 架构 + Telegram 风格消息状态机
-- 目标：保留 slack-clone 的性能优化，添加 Agent 支持和消息状态追踪
--

-- ============================================
-- Custom types
-- ============================================
create type public.app_permission as enum ('channels.delete', 'messages.delete', 'agents.manage');
create type public.app_role as enum ('admin', 'moderator');
create type public.user_status as enum ('ONLINE', 'OFFLINE', 'AWAY');
create type public.message_status as enum ('SENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED');
create type public.participant_type as enum ('human', 'agent');

-- ============================================
-- USERS (基于 slack-clone)
-- ============================================
create table public.users (
  id          uuid references auth.users not null primary key,
  username    text,
  display_name text,
  avatar_url  text,
  status      user_status default 'OFFLINE'::public.user_status,
  last_seen_at timestamp with time zone,
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null
);
comment on table public.users is 'Human participants (profile data for each user).';
comment on column public.users.id is 'References the internal Supabase Auth user.';

-- ============================================
-- AGENTS (新增：Agent 参与者)
-- ============================================
create table public.agents (
  id            uuid primary key default gen_random_uuid(),
  owner_id      uuid references public.users on delete cascade not null,
  agent_name    text not null,
  display_name  text,
  avatar_url    text,
  runtime       text,  -- windsurf, cursor, etc.
  status        user_status default 'OFFLINE'::public.user_status,
  last_seen_at  timestamp with time zone,
  metadata      jsonb,  -- {project_dir, terminal, etc.}
  created_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(owner_id, agent_name)
);
comment on table public.agents is 'AI Agent participants owned by users.';
create index idx_agents_owner on agents(owner_id);

-- ============================================
-- CHANNELS (基于 slack-clone，重命名概念为 conversations)
-- ============================================
create table public.channels (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  slug          text not null unique,
  created_by_type participant_type not null,
  created_by_id   uuid not null,
  type          text default 'direct',  -- 'direct' | 'group'
  title         text,
  last_message_at timestamp with time zone
);
comment on table public.channels is 'Conversations (direct or group chat).';
create index idx_channels_created_by on channels(created_by_type, created_by_id);

-- ============================================
-- CHANNEL PARTICIPANTS (新增：对话参与者)
-- ============================================
create table public.channel_participants (
  id              bigint generated by default as identity primary key,
  channel_id      bigint references public.channels on delete cascade not null,
  participant_type participant_type not null,
  participant_id  uuid not null,
  joined_at       timestamp with time zone default timezone('utc'::text, now()) not null,
  last_read_at    timestamp with time zone,
  unique(channel_id, participant_type, participant_id)
);
comment on table public.channel_participants is 'Participants in each conversation.';
create index idx_channel_participants_channel on channel_participants(channel_id);
create index idx_channel_participants_participant on channel_participants(participant_type, participant_id);

-- ============================================
-- MESSAGES (扩展 slack-clone，添加状态机)
-- ============================================
create table public.messages (
  id              bigint generated by default as identity primary key,
  inserted_at     timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  message         text,
  payload         jsonb,  -- 结构化交互 {type: 'choice'|'confirm'|'form', ...}
  sender_type     participant_type not null,
  sender_id       uuid not null,
  channel_id      bigint references public.channels on delete cascade not null,
  status          message_status default 'SENT'::public.message_status,
  reply_to_message_id bigint references public.messages,
  edited_at       timestamp with time zone
);
comment on table public.messages is 'Individual messages with Telegram-style status tracking.';
create index idx_messages_channel on messages(channel_id, inserted_at desc);
create index idx_messages_sender on messages(sender_type, sender_id);

-- ============================================
-- MESSAGE RECEIPTS (新增：Telegram 风格送达/已读状态)
-- ============================================
create table public.message_receipts (
  id              bigint generated by default as identity primary key,
  message_id      bigint references public.messages on delete cascade not null,
  participant_type participant_type not null,
  participant_id  uuid not null,
  delivered_at    timestamp with time zone,
  read_at         timestamp with time zone,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(message_id, participant_type, participant_id)
);
comment on table public.message_receipts is 'Message delivery and read receipts (Telegram-style).';
create index idx_message_receipts_message on message_receipts(message_id);

-- ============================================
-- FILES (新增：文件存储)
-- ============================================
create table public.files (
  id              uuid primary key default gen_random_uuid(),
  sha256          text unique not null,
  storage_path    text not null,
  filename        text not null,
  mime_type       text not null,
  size_bytes      bigint not null,
  uploaded_by_type participant_type not null,
  uploaded_by_id  uuid not null,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null
);
comment on table public.files is 'File attachments stored in Supabase Storage.';

-- ============================================
-- MESSAGE FILES (新增：消息-文件关联)
-- ============================================
create table public.message_files (
  message_id      bigint references public.messages on delete cascade not null,
  file_id         uuid references public.files on delete cascade not null,
  idx             integer not null,
  primary key (message_id, idx)
);
comment on table public.message_files is 'Links files to messages.';

-- ============================================
-- USER ROLES (保留 slack-clone RBAC)
-- ============================================
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references public.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- ============================================
-- ROLE PERMISSIONS (保留 slack-clone RBAC)
-- ============================================
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

-- ============================================
-- FUNCTIONS
-- ============================================

-- RBAC authorize function (保留 slack-clone)
create function public.authorize(
  requested_permission app_permission
)
returns boolean as $$
declare
  bind_permissions int;
begin
  select count(*)
  from public.role_permissions
  where role_permissions.permission = authorize.requested_permission
    and role_permissions.role = (auth.jwt() ->> 'user_role')::public.app_role
  into bind_permissions;
  
  return bind_permissions > 0;
end;
$$ language plpgsql security definer set search_path = public;

-- Handle new user (保留 slack-clone)
create function public.handle_new_user() 
returns trigger as $$
declare is_admin boolean;
begin
  insert into public.users (id, username, display_name)
  values (new.id, new.email, split_part(new.email, '@', 1));
  
  select count(*) = 1 from auth.users into is_admin;
  
  if position('+supaadmin@' in new.email) > 0 then
    insert into public.user_roles (user_id, role) values (new.id, 'admin');
  elsif position('+supamod@' in new.email) > 0 then
    insert into public.user_roles (user_id, role) values (new.id, 'moderator');
  end if;
  
  return new;
end;
$$ language plpgsql security definer set search_path = auth, public;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Update channel timestamp on new message
create function public.update_channel_timestamp()
returns trigger as $$
begin
  update public.channels
  set last_message_at = now()
  where id = new.channel_id;
  return new;
end;
$$ language plpgsql;

create trigger on_message_insert
  after insert on public.messages
  for each row execute function public.update_channel_timestamp();

-- Auto-create message receipts for all participants (Telegram 风格)
create function public.create_message_receipts()
returns trigger as $$
begin
  insert into public.message_receipts (message_id, participant_type, participant_id)
  select new.id, cp.participant_type, cp.participant_id
  from public.channel_participants cp
  where cp.channel_id = new.channel_id
    and not (cp.participant_type = new.sender_type and cp.participant_id = new.sender_id);
  return new;
end;
$$ language plpgsql;

create trigger on_message_create_receipts
  after insert on public.messages
  for each row execute function public.create_message_receipts();

-- ============================================
-- ROW LEVEL SECURITY (简化版，基于 slack-clone)
-- ============================================

alter table public.users enable row level security;
alter table public.agents enable row level security;
alter table public.channels enable row level security;
alter table public.channel_participants enable row level security;
alter table public.messages enable row level security;
alter table public.message_receipts enable row level security;
alter table public.files enable row level security;
alter table public.message_files enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

-- Users: 所有认证用户可读，只能更新自己
create policy "Allow logged-in read access" on public.users for select using ( auth.role() = 'authenticated' );
create policy "Allow individual insert access" on public.users for insert with check ( auth.uid() = id );
create policy "Allow individual update access" on public.users for update using ( auth.uid() = id );

-- Agents: 只能操作自己拥有的 agent
create policy "Allow logged-in read access" on public.agents for select using ( auth.role() = 'authenticated' );
create policy "Allow owner CRUD access" on public.agents for all using ( auth.uid() = owner_id );

-- Channels: 所有认证用户可读（简化版，类似 slack-clone）
create policy "Allow logged-in read access" on public.channels for select using ( auth.role() = 'authenticated' );
create policy "Allow individual insert access" on public.channels for insert with check ( 
  (created_by_type = 'human' and auth.uid() = created_by_id)
);
create policy "Allow creator delete access" on public.channels for delete using ( 
  (created_by_type = 'human' and auth.uid() = created_by_id)
);
create policy "Allow authorized delete access" on public.channels for delete using ( authorize('channels.delete') );

-- Channel Participants: 所有认证用户可读
create policy "Allow logged-in read access" on public.channel_participants for select using ( auth.role() = 'authenticated' );
create policy "Allow insert for channel members" on public.channel_participants for insert with check ( auth.role() = 'authenticated' );

-- Messages: 所有认证用户可读（简化版，类似 slack-clone）
create policy "Allow logged-in read access" on public.messages for select using ( auth.role() = 'authenticated' );
create policy "Allow individual insert access" on public.messages for insert with check ( 
  (sender_type = 'human' and auth.uid() = sender_id)
  or
  (sender_type = 'agent' and exists (
    select 1 from public.agents a
    where a.id = sender_id and a.owner_id = auth.uid()
  ))
);
create policy "Allow individual update access" on public.messages for update using ( 
  (sender_type = 'human' and auth.uid() = sender_id)
);
create policy "Allow individual delete access" on public.messages for delete using ( 
  (sender_type = 'human' and auth.uid() = sender_id)
);
create policy "Allow authorized delete access" on public.messages for delete using ( authorize('messages.delete') );

-- Message Receipts: 所有认证用户可读
create policy "Allow logged-in read access" on public.message_receipts for select using ( auth.role() = 'authenticated' );
create policy "Allow update own receipts" on public.message_receipts for update using ( 
  (participant_type = 'human' and auth.uid() = participant_id)
);

-- Files: 所有认证用户可读
create policy "Allow logged-in read access" on public.files for select using ( auth.role() = 'authenticated' );
create policy "Allow individual insert access" on public.files for insert with check ( 
  (uploaded_by_type = 'human' and auth.uid() = uploaded_by_id)
  or
  (uploaded_by_type = 'agent' and exists (
    select 1 from public.agents a
    where a.id = uploaded_by_id and a.owner_id = auth.uid()
  ))
);

-- Message Files: 所有认证用户可读
create policy "Allow logged-in read access" on public.message_files for select using ( auth.role() = 'authenticated' );

-- User Roles: 只能读取自己的角色
create policy "Allow individual read access" on public.user_roles for select using ( auth.uid() = user_id );

-- ============================================
-- REALTIME (基于 slack-clone，添加新表)
-- ============================================

-- Send "previous data" on change (关键性能优化)
alter table public.users replica identity full; 
alter table public.agents replica identity full; 
alter table public.channels replica identity full;
alter table public.messages replica identity full;
alter table public.message_receipts replica identity full;

begin; 
  drop publication if exists supabase_realtime; 
  create publication supabase_realtime;  
commit;

-- Add tables to the publication
alter publication supabase_realtime add table public.users;
alter publication supabase_realtime add table public.agents;
alter publication supabase_realtime add table public.channels;
alter publication supabase_realtime add table public.channel_participants;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.message_receipts;

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Create test user (保留 slack-clone)
create or replace function public.create_user(
    email text
) returns uuid
    security definer
    set search_path = auth
as $$
  declare
  user_id uuid;
begin
  user_id := extensions.uuid_generate_v4();
  
  insert into auth.users (id, email)
    values (user_id, email)
    returning id into user_id;

    return user_id;
end;
$$ language plpgsql;

-- Get or create direct conversation between user and agent
create or replace function public.get_or_create_direct_conversation(
  p_user_id uuid,
  p_agent_id uuid
) returns bigint
language plpgsql
security definer
as $$
declare
  v_channel_id bigint;
begin
  -- Try to find existing direct conversation
  select c.id into v_channel_id
  from public.channels c
  where c.type = 'direct'
    and exists (
      select 1 from public.channel_participants cp1
      where cp1.channel_id = c.id
        and cp1.participant_type = 'human'
        and cp1.participant_id = p_user_id
    )
    and exists (
      select 1 from public.channel_participants cp2
      where cp2.channel_id = c.id
        and cp2.participant_type = 'agent'
        and cp2.participant_id = p_agent_id
    )
  limit 1;

  -- Create if not exists
  if v_channel_id is null then
    insert into public.channels (slug, created_by_type, created_by_id, type)
    values (
      'direct-' || p_user_id::text || '-' || p_agent_id::text,
      'human',
      p_user_id,
      'direct'
    )
    returning id into v_channel_id;

    -- Add participants
    insert into public.channel_participants (channel_id, participant_type, participant_id)
    values 
      (v_channel_id, 'human', p_user_id),
      (v_channel_id, 'agent', p_agent_id);
  end if;

  return v_channel_id;
end;
$$;
