-- ============================================
-- Cue Stack Supabase Schema v1.0
-- Agent Telegram Architecture
-- ============================================

-- ============================================
-- 用户表（Human Participants）
-- ============================================
CREATE TABLE public.users (
  id UUID REFERENCES auth.users PRIMARY KEY,
  username TEXT UNIQUE,
  display_name TEXT,
  avatar_url TEXT,
  status TEXT DEFAULT 'OFFLINE',  -- ONLINE/OFFLINE/AWAY
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================
-- Agent 表（Agent Participants）
-- ============================================
CREATE TABLE public.agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES public.users NOT NULL,
  agent_name TEXT NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  runtime TEXT,
  status TEXT DEFAULT 'OFFLINE',
  last_seen_at TIMESTAMPTZ,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(owner_id, agent_name)
);

-- ============================================
-- 对话表
-- ============================================
CREATE TABLE public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL DEFAULT 'direct',
  title TEXT,
  created_by_type TEXT NOT NULL,
  created_by_id UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  last_message_at TIMESTAMPTZ
);

-- ============================================
-- 对话参与者表
-- ============================================
CREATE TABLE public.conversation_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id UUID REFERENCES public.conversations ON DELETE CASCADE NOT NULL,
  participant_type TEXT NOT NULL,
  participant_id UUID NOT NULL,
  joined_at TIMESTAMPTZ DEFAULT now(),
  last_read_at TIMESTAMPTZ,
  UNIQUE(conversation_id, participant_type, participant_id)
);

-- ============================================
-- 消息表（核心）
-- ============================================
CREATE TYPE message_status AS ENUM (
  'SENDING',
  'SENT',
  'DELIVERED',
  'READ',
  'FAILED'
);

CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id UUID REFERENCES public.conversations ON DELETE CASCADE NOT NULL,
  sender_type TEXT NOT NULL CHECK (sender_type IN ('human', 'agent')),
  sender_id UUID NOT NULL,
  content TEXT NOT NULL,
  payload JSONB,
  status message_status DEFAULT 'SENT',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  edited_at TIMESTAMPTZ,
  reply_to_message_id BIGINT REFERENCES public.messages
);

-- ============================================
-- 消息送达/已读状态表
-- ============================================
CREATE TABLE public.message_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT REFERENCES public.messages ON DELETE CASCADE NOT NULL,
  participant_type TEXT NOT NULL,
  participant_id UUID NOT NULL,
  delivered_at TIMESTAMPTZ,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(message_id, participant_type, participant_id)
);

-- ============================================
-- 文件表
-- ============================================
CREATE TABLE public.files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sha256 TEXT UNIQUE NOT NULL,
  storage_path TEXT NOT NULL,
  filename TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  uploaded_by_type TEXT NOT NULL,
  uploaded_by_id UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================
-- 消息-文件关联表
-- ============================================
CREATE TABLE public.message_files (
  message_id BIGINT REFERENCES public.messages ON DELETE CASCADE NOT NULL,
  file_id UUID REFERENCES public.files NOT NULL,
  idx INTEGER NOT NULL,
  PRIMARY KEY (message_id, idx)
);

-- ============================================
-- 索引
-- ============================================
CREATE INDEX idx_messages_conversation ON messages(conversation_id, created_at DESC);
CREATE INDEX idx_messages_sender ON messages(sender_type, sender_id);
CREATE INDEX idx_conversation_participants_conversation ON conversation_participants(conversation_id);
CREATE INDEX idx_conversation_participants_participant ON conversation_participants(participant_type, participant_id);
CREATE INDEX idx_message_receipts_message ON message_receipts(message_id);
CREATE INDEX idx_agents_owner ON agents(owner_id);

-- ============================================
-- RLS 策略
-- ============================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_files ENABLE ROW LEVEL SECURITY;

-- Users: 所有人可读，只能更新自己
CREATE POLICY "Users read all" ON public.users FOR SELECT USING (true);
CREATE POLICY "Users update own" ON public.users FOR UPDATE USING (auth.uid() = id);

-- Agents: 只能操作自己拥有的 agent
CREATE POLICY "Agents read own" ON public.agents FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Agents CRUD own" ON public.agents FOR ALL USING (auth.uid() = owner_id);

-- Conversations: 只能访问自己参与的对话
CREATE POLICY "Conversations read own" ON public.conversations FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants cp
      WHERE cp.conversation_id = conversations.id
        AND cp.participant_type = 'human'
        AND cp.participant_id = auth.uid()
    )
  );

CREATE POLICY "Conversations create" ON public.conversations FOR INSERT
  WITH CHECK (
    (created_by_type = 'human' AND created_by_id = auth.uid())
  );

-- Participants: 只能访问自己参与的对话的参与者
CREATE POLICY "Participants read own conversations" ON public.conversation_participants FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants cp
      WHERE cp.conversation_id = conversation_participants.conversation_id
        AND cp.participant_type = 'human'
        AND cp.participant_id = auth.uid()
    )
  );

-- Messages: 只能访问自己参与的对话的消息
CREATE POLICY "Messages read own conversations" ON public.messages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants cp
      WHERE cp.conversation_id = messages.conversation_id
        AND cp.participant_type = 'human'
        AND cp.participant_id = auth.uid()
    )
  );

CREATE POLICY "Messages insert own" ON public.messages FOR INSERT
  WITH CHECK (
    (sender_type = 'human' AND sender_id = auth.uid())
    OR
    (sender_type = 'agent' AND EXISTS (
      SELECT 1 FROM public.agents a
      WHERE a.id = sender_id AND a.owner_id = auth.uid()
    ))
  );

-- Receipts: 只能访问自己参与的对话的回执
CREATE POLICY "Receipts read own" ON public.message_receipts FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.messages m
      JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id
      WHERE m.id = message_receipts.message_id
        AND cp.participant_type = 'human'
        AND cp.participant_id = auth.uid()
    )
  );

-- Files: 只能访问自己上传的或自己参与的对话中的文件
CREATE POLICY "Files read own" ON public.files FOR SELECT
  USING (
    (uploaded_by_type = 'human' AND uploaded_by_id = auth.uid())
    OR
    EXISTS (
      SELECT 1 FROM public.message_files mf
      JOIN public.messages m ON m.id = mf.message_id
      JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id
      WHERE mf.file_id = files.id
        AND cp.participant_type = 'human'
        AND cp.participant_id = auth.uid()
    )
  );

-- ============================================
-- Realtime 发布
-- ============================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.conversations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.conversation_participants;
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.message_receipts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.agents;
ALTER PUBLICATION supabase_realtime ADD TABLE public.users;

-- ============================================
-- 触发器
-- ============================================

-- 自动创建 users 记录
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, username, display_name)
  VALUES (NEW.id, NEW.email, SPLIT_PART(NEW.email, '@', 1));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 更新 conversation.updated_at
CREATE OR REPLACE FUNCTION public.update_conversation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.conversations
  SET updated_at = now(), last_message_at = now()
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_message_insert
  AFTER INSERT ON public.messages
  FOR EACH ROW EXECUTE FUNCTION public.update_conversation_timestamp();

-- 自动创建 message_receipts
CREATE OR REPLACE FUNCTION public.create_message_receipts()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.message_receipts (message_id, participant_type, participant_id)
  SELECT NEW.id, cp.participant_type, cp.participant_id
  FROM public.conversation_participants cp
  WHERE cp.conversation_id = NEW.conversation_id
    AND NOT (cp.participant_type = NEW.sender_type AND cp.participant_id = NEW.sender_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_message_create_receipts
  AFTER INSERT ON public.messages
  FOR EACH ROW EXECUTE FUNCTION public.create_message_receipts();
